# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$HOME/.cargo/bin:$PATH

# Set vim as base editor
export VISUAL=vim
export EDITOR="$VISUAL"


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
   aws
   colorize
   docker
   docker-compose
   git
   globalias
   zsh-autosuggestions
   history-substring-search
   zsh-completions
)

source $ZSH/oh-my-zsh.sh

# User Configuration

export GOPATH=~/.go
export GOBIN=~/.go/build/bin

# Load custom configuration files and scripts from '~/.zsh'
for i in $HOME/.zsh/*; do;
    test -r "$i" && source "$i"
done

# Treatwell specific
if [ -f ~/.treatwellrc ]; then
    source ~/.treatwellrc
    twist-enable
fi
