# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH

# Set vim as base editor
export VISUAL=vim
export EDITOR="$VISUAL"


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
   aws
   colorize
   docker
   docker-compose
   git
   globalias
   zsh-autosuggestions
   history-substring-search
   zsh-completions
)

source $ZSH/oh-my-zsh.sh

# User Configuration

export GOPATH=~/.go
export GOBIN=~/.go/build/bin

# Load custom configuration files and scripts from '~/.zsh'
for i in $HOME/.zsh/*; do;
    test -r "$i" && source "$i"
done

# JEnv setup (https://www.jenv.be/)
export PATH="$PATH:$HOME/.jenv/bin"
eval "$(jenv init -)"

# Maven
export M2_HOME=/opt/maven
export PATH="$PATH:$M2_HOME/bin"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
# Elixir 
export PATH="$PATH:$HOME/.kiex/bin"
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/balys/Applications/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/balys/Applications/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/balys/Applications/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/balys/Applications/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

